name: Deploy
on:
  push:
    branches:
      - master

env:
  DEP_PATH: src/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out master
        uses: actions/checkout@master
        with:
          safety_args: '-i 35015'
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{42361526-08b6-4595-a4f2-e23d7880271a}}
          HEROKU_APP_NAME: "hkbucomp7940-21470561-bot"  # Rename this to the app of your Heroku app.
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main